service: serverless-hw
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  iamRoleStatements:
       - Effect: Allow
         Action:
             - "dynamodb:PutItem"
             - "dynamodb:GetItem"
             - "dynamodb:UpdateItem"
             - "dynamodb:DeleteItem"
             - "dynamodb:BatchGetItem"
             - "dynamodb:BatchWriteItem"
             - "dynamodb:Scan"
             - "dynamodb:Query"
         Resource:
             - "arn:aws:dynamodb:us-east-1:*:*"

 # environment:
   # TABLE_NAME: purchares

functions:
   crud_app:
       handler: handler.main_handler
       events:
           - http:
               path: main_handler
               method: ANY
